name: firebase deploy
run-name: ${{github.workflow}} - ${{github.event.head_commit.message || github.event.pull_request.title}}

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25.4.0'
          cache: 'npm'
      - name: install packages
        run: npm ci
      - name: run auto stest
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25.4.0'
      - name: install packages
        run: npm ci
      - name: app build
        env:
          VITE_SUPABASE_URL: ${{secrets.VITE_SUPABASE_URL}}
          VITE_SUPABASE_PROJECT_KEY: ${{secrets.VITE_SUPABASE_PROJECT_KEY}}
        run: npm run build
      - name: Archive build file artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-artifact
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup Node.js with cache
        uses: actions/setup-node@v6
        with:
          node-version: '25.4.0'
          cache: 'npm'
      - name: install firebase cli
        run: npm install --save-dev firebase-tools
      - name: decode firebase service account key to authenticate
        run: |
          echo "${{secrets.FIREBASE_KEY}}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{github.workspace}}/firebase-key.json" >> $GITHUB_ENV
      - name: select active space
        run: |
          ./node_modules/.bin/firebase use ${{secrets.FIREBASE_PROJECT_ID}}
      - name: download build artifact
        uses: actions/download-artifact@v6
        with:
          name: dist-artifact
          path: dist
      - name: deploy to firebase hosting
        run: |
          ./node_modules/.bin/firebase deploy
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: delete GOOGLE_APPLICATION_CREDENTIALS
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
