name: firebase deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25.4.0'
      - name: install packages
        run: npm ci
      - name: app build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: setup Node.js with cache
        uses: actions/setup-node@v6
        with:
          node-version: '25.4.0'
          cache: 'npm'
      - name: install packages
        run: npm ci
      - name: install firebase cli
        run: npm install --save-dev firebase-tools
      - name: decode firebase service account key
        run: |
          echo "${{secrets.FIREBASE_KEY}}" | base64 -d > ./firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{github.workspace}}/firebase-key.json" >> $GITHUB_ENV
      - name: select active space
        run: |
          ./node_module/.bin/firebase use ${{secrets.FIREBASE_PROJECT_KEY}}
      - name: deploy to firebase hosting
        run: |
          ./node_module/.bin/firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: delete GOOGLE_APPLICATION_CREDENTIALS
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
